# apiVersion: v1
# kind: Pod
# metadata:
#   name: product-api
#   labels:
#     component: product-api
# spec: 
#   containers:
#     - name: product-api
#       image: edwardkemper/product-api
#       ports:
#         - containerPort: 5002

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
spec: 
  replicas: 2
  selector:
    matchLabels:
      component: product-api
  template:
    metadata:
      labels:
        component: product-api

    spec: 
      containers:
        - name: product-api
          image: edwardkemper/product-api
          ports:
            - containerPort: 5002
            

