
#  --> for the pod configuration, this is used. 
# --> note the file was renamed from store-pod.yaml to store-deployment.yaml


# apiVersion: v1
# kind: Pod
# metadata:
#   name: store-app
#   labels:
#     component: store
# spec:
#   containers:
#     - name: store
#       image: edwardkemper/store-app
#       ports: 
#         - containerPort: 80



#  -- > here is the deployment configuration -->

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: store
spec:
  replicas: 3   # number of pods to run
  selector: 
    matchLabels: 
      component: store
  template: # defining the pod that the deployment will manage
    metadata:
      labels:
        component: store # the label that the deployment matches to 
    spec:
      containers:
        - name: store
          image: edwardkemper/store-app
          ports:
            - containerPort: 80


